= Language Choice

[TIP]
====
Status: Draft +
Created: 5.12.2025 +
Author: Seepick
====

[QUESTION]
====
Which programming language to choose?
====

* Java or Kotlin?
** not really any other: Definitely no Scala, Clojure, ... and no non-JVM languages (Go, Rust, Python, C#, ...).

* interoperability; always possible to fall back to java code and "java native libs"
* using Lombok is an indication we want Kotlin:
** from plain java, to Lombok, to kotlin
** native data classes support, properties, prop-initializing-ctor; from final to val

Main points for Kotlin:

* Similar to java; fully interoperable (could use Spring)
* concise (less boilerplate, less verbose); cleaner/less code, faster development
* Null safety built into the type system
* Extension functions
* Functional (functions as first-class citizens; higher-order functions)
* Immutability by default (collections)
* JetBrains supported, tooling (IDE!), ecosystem

Side points for Kotlin:

* Concise lambda definition (custom DSLs)
* Type inference, smart casts
* Bypass type erasure with inline functions and reified generics (have type parameter available at runtime, no more typeOf magic)
* Default and named parameters
* String templating
* Coroutines (async)

Some things Java was able to catch up a bit (yet sometimes a bit poorly implemented): lambdas, method reference, pattern matching, records

Downsides for Kotlin:

* Not as popular (tools, libs, documentation, experience/skill)
* Compiler is not as highly optimized (fast) as Java's
* 100% interoperable regarding the language itself, but with some (older) frameworks there are some incompatibilities in paradigm
