= Programming Language

[QUESTION]
====
Which programming language to use?
====

[TIP]
====
Status: Proposed +
Created: 5.12.2025 +
Author: Seepick
====

*Context*

* We prefer a JVM tech stack, thus mainly Java or Kotlin (no Scala, Clojure, ...)
** Non non-JVM language like Go, Rust, Python, ...
** C# is a sophisticated option and used widely though.
* A natural evolution from plain Java, adding Lombok, and then to Kotlin.
** Using Lombok is an indication we want Kotlin (and Guava's immutable data structures).
** Native data classes support, properties, prop-initializing-ctor; from final to val.

*Options*

Main points for Kotlin:

* Interoperability
** Allows smooth migration (Java and Kotlin live side-by-side)
** Always possible to fall back to java code and "java native libs" (could use Spring)
* Concise (less boilerplate, less verbose); cleaner/less code, faster development
* Null safety built into the type system
* Extension functions
* Functional (functions as first-class citizens; higher-order functions)
* Immutability by default (collections)
* JetBrains supported, tooling (IDE!), ecosystem

Side points for Kotlin:

* Concise lambda definition (custom DSLs)
* Type inference, smart casts
* Bypass type erasure with inline functions and reified generics (have type parameter available at runtime, no more typeOf magic)
* Default and named parameters
* String templating
* Coroutines (async)

Some things Java was able to catch up a bit (yet sometimes a bit poorly implemented): lambdas, method reference, pattern matching, records.

Downsides for Kotlin:

* Not as popular (tools, libs, documentation, experience/skill)
* Compiler is not as highly optimized (fast) as Java's
* 100% interoperable regarding the language itself, but with some (older) frameworks there are some incompatibilities in paradigm

*Decision*

* Kotlin is a modern and Java-familiar language, supporting the whole Java ecosystem (safe bet), allowing safe and rapid development.
* It gets more and more popular, additionally with JetBrains as the company behind it, major support.
