= Scheduler Solution

[QUESTION]
====
Which library/service to use to implement time-based tasks?
====

[TIP]
====
Status: Draft +
Created: 1.12.2025 +
Author: Seepick
====

*Context*

* We need to run jobs regularly in a cronjob way.
* We need to define future tasks programmatically.
* For testing, we need a way to trigger them from externally (guarantee restricted access).

*Options*

* Spring scheduler standalone could be used.
* Quartz https://www.quartz-scheduler.org
** enterprise (heavy, slow) scheduler; the "platzhirsch", used to be the one and only; decades
** but the pros comes with cons: outdated, verbose APIs
** features: persisted in DB (requires 10+! tables), retry, clustering, prioritization etc
** no monitoring (grafana, jaeger)
* JobRunr https://www.jobrunr.io
** lightweight, modern; RDBMS (and NoSQL)
** features: distributed, dashboard, retry
** Don't "store code" in the future task, as the code might has changed until the task is executed!
* db-scheduler https://github.com/kagkarlsson/db-scheduler
** lightweight: performant, minimal deps; still offer what's need: persistence, cluster
* OPEN: maybe there is a mature enough kotlin library which leverages coroutines?
** link:https://github.com/Pool-Of-Tears/KtScheduler[KtScheduler] seems like a small hobby project...

*Resources*

* https://www.jobrunr.io/en/blog/2024-10-31-task-schedulers-java-modern-alternatives-to-quartz/
