= Boot or Ktor?

[QUESTION]
====
Which modern, non-intrusive web framework to use for communicating JSON-RPC-over-HTTP (a.k.a.
ReST)?
====

[TIP]
====
Status: Accepted +
Created: 5.12.2025 +
Author: Seepick
====

*Context*

* The web framework is usually also dictating a bigger part of the application: dependency injection, configuration, etc.
** Especially with heavy-weight frameworks like Spring Boot and the enterprise implementations are covering more than just "being a fancy servlet".
* We need something more lightweight, fast, highly configurable (test needs rewiring), and modern.

*Options*

. Spring Boot/Web
** Most common in JVM world.
** very opinionated (convention over configuration like)
** Very much like maven, “super strict, either our or no way”
** Its pro is its con: beneficial at beginning, but no power user custom things (fighting the convention)
** Difficult to start only parts of the application (testing), in isolation (parallel testing; @DirtiesContext), due to classpath scanning and annotations usage.
. Ktor
** Lightweight, modern (coroutines), multiplatform (typescript), server and client.
** Less popular (getting better; dev familiarity), less mature, smaller community/ecosystem (libs, plugins, documentation).
** Much needs handwritten; some good (code, control), some bad (OpenAPI generation)
** Everything is code (instead of annotations), there is a beautifully simple way to do it, and so extremely flexible, that every test strategy we can imagine can be implemented.
. Micronaut
. Quarkus
** Currently a very popular alternative to the aforementioned.
** Nore lightweight (build/start time, lower resource consumption) than JEE implementations
** Kube-native: pre-built integrations increasing productivity.
. JEE JAX-RS
** Jersey, ReST-easy, ... the big ones.

Or maybe Spring with Kotlin?

* More and more attention from Spring towards Kotlin; more support.
* Also interesting: link:https://docs.spring.io/spring-integration/reference/kotlin-dsl.html[Spring Kotlin DSL]
* See link:https://github.com/spring-attic/spring-fu/tree/main/kofu[kofu] for Spring experimental support to make it look like ktor.

*Decision*

* We use Ktor, fitting in the tech-stack for a modern, safe, rapid development approach.
* It's lightweight, requires minimal boilerplate
* Code as first-class-citizens (no annotations/properties)
* It's coroutine-based thus extremely efficient
* Fast startup and low memory footprint (compared to Spring)
* Developed by JetBrains which creates synergies (Kotlin, Exposed, Serialization)
