= Webframework

[QUESTION]
====
Which modern, non-intrusive web framework to use for communicating JSON-RPC-over-HTTP (a.k.a.
ReST)?
====

[TIP]
====
Status: Accepted +
Created: 5.12.2025 +
Author: Seepick
====

* The web framework is usually also dictating a bigger part of the application: dependency injection, configuration, etc.
** Especially with heavy-weight frameworks like Spring Boot and the enterprise implementations are covering more than just "being a fancy servlet".
* We need something more lightweight, fast, highly configurable (test needs rewiring), and modern.

*Options*

. Spring Boot/Web
** Most common in JVM world.
** very opinionated (convention over configuration like)
** Very much like maven, “super strict, either our or no way”
** Its pro is its con: beneficial at beginning, but no power user custom things (fighting the convention)
** Difficult to start only parts of the application (testing), in isolation (parallel testing; @DirtiesContext), due to classpath scanning and annotations usage.
. Ktor
** Lightweight, modern (coroutines), multiplatform (typescript), server and client.
** Less popular (getting better), less mature, smaller community (documentation).
** Much needs handwritten; some good (code, control), some bad (OpenAPI generation)
** Everything is code (instead of annotations), there is a beautifully simple way to do it, and so extremely flexible, that every test strategy we can imagine can be implemented.
. JEE JAX-RS
** Jersey, ReST-easy, ... the big ones.
. Quarkus
** More popular, more lightweight than JEE implementations; cloud native.

Spring and Kotlin?

* more and more attention from Spring towards Kotlin; more support
* see link:https://github.com/spring-attic/spring-fu/tree/main/kofu[kofu] for spring experimental support to make it look like ktor
* also interesting: link:https://docs.spring.io/spring-integration/reference/kotlin-dsl.html[Spring Kotlin DSL]

*Conclusion*

* We use Ktor, fitting in the tech-stack for a modern, safe, rapid development approach.
