# set alias for "dc=docker compose"
# start in detached mode (background)
# $ dc up -d
# $ dc down
# live logs:
# $ dc logs -f db
# print running containers
# $ dc ps

services:

  diamond:
    container_name: diamond
    restart: unless-stopped
    # assuming you did a: `./gradlew :app:publishImageToLocalRegistry
    image: diamond:latest
    # to build from source... requires Dockerfile though
    #    build: .
    ports:
      - "8080:8080"
    environment:
      DATABASE_JDBCURL: jdbc:oracle:thin:@oracle-db:1521/XEPDB1
      DATABASE_USERNAME: demo
      DATABASE_PASSWORD: demo123
      # TODO wiremock
      EXTERN_POSTSSERVICEBASEURL: url
      KTOR_PORT: 8080
    depends_on:
      oracle-db:
        condition: service_healthy
  #    volumes:
  #      - ${JAVA_HOME}/lib/security:/opt/java/openjdk/lib/security

  oracle-db:
    image: gvenzl/oracle-xe:21-slim-faststart
    container_name: oracle-xe-21
    restart: unless-stopped
    environment:
      ORACLE_PASSWORD: Oracle12345!
      APP_USER: demo
      APP_USER_PASSWORD: demo123
    ports:
      - "1521:1521"
    volumes:
      - oracle_xe_data:/opt/oracle/oradata # Persistent database files
    healthcheck:
      test: [ "CMD", "sqlplus", "-L", "demo/demo123@//localhost:1521/XEPDB1", "<<<", "SELECT 1 FROM DUAL;" ]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 120s
volumes:
  oracle_xe_data:
    driver: local
