kotlin.code.style=official
# plugins (kotlin-MP, detekt) use deprecated gradle features; disable as we can't do anything about it...
# alternatively can be set to: all, summary
org.gradle.warning.mode=none
# see: https://docs.gradle.org/9.2.1/userguide/configuration_cache_enabling.html
org.gradle.configuration-cache=true
org.gradle.configuration-cache.parallel=true
# for CI server: ? ./gradlew -Dorg.gradle.configuration-cache.read-only=true
detekt.use.worker.api=true
