sonar.organization=seepick
sonar.projectKey=seepick_diamond

# relative paths to source directories. More details and properties are described at
# https://docs.sonarsource.com/sonarqube-cloud/advanced-setup/analysis-scope/
sonar.sources=src
# See: https://docs.sonarsource.com/sonarqube-community-build/project-administration/setting-analysis-scope/excluding-files-based-on-patterns
sonar.exclusions=**/buildSrc/build/generated-sources/**

sonar.coverage.jacoco.xmlReportPaths=build/reports/kover/report.xml
