package nl.uwv.smz.diamond.persistence.impl

import arrow.core.Either
import arrow.core.left
import arrow.core.raise.either
import io.github.oshai.kotlinlogging.KotlinLogging.logger
import nl.uwv.smz.diamond.domain.failure.Failure
import nl.uwv.smz.diamond.domain.model.Crystal
import nl.uwv.smz.diamond.domain.model.CrystalCreate
import nl.uwv.smz.diamond.domain.model.CrystalId
import nl.uwv.smz.diamond.domain.model.CrystalUpdate
import nl.uwv.smz.diamond.domain.model.Gram
import nl.uwv.smz.diamond.domain.model.Page
import nl.uwv.smz.diamond.domain.model.PageMeta
import nl.uwv.smz.diamond.domain.model.PageRequest
import nl.uwv.smz.diamond.persistence.api.CrystalRepo
import org.jetbrains.exposed.dao.UUIDEntity
import org.jetbrains.exposed.dao.UUIDEntityClass
import org.jetbrains.exposed.dao.id.EntityID
import org.jetbrains.exposed.sql.Database
import java.util.UUID
import kotlin.uuid.toJavaUuid
import kotlin.uuid.toKotlinUuid

internal class CrystalDaoEntity(id: EntityID<UUID>) : UUIDEntity(id) {
    var weightInGrams by CrystalTable.weightInGrams

    companion object : UUIDEntityClass<CrystalDaoEntity>(CrystalTable)
}

fun <T> List<T>.toPage(pageRequest: PageRequest, hasMore: Boolean) = Page(
    meta = PageMeta(
        skip = pageRequest.skip,
        take = pageRequest.take,
        hasMore = hasMore,
    ),
    items = this,
)

internal class CrystalExposedDaoRepo(private val db: Database) : CrystalRepo {

    private val log = logger {}

    override suspend fun selectAll(pageRequest: PageRequest) = either {
        suspendTransaction(db) {
            log.debug { "selectAll($pageRequest)" }
            selectPagedCrystals(pageRequest).bind()
        }
    }

    override suspend fun selectById(id: CrystalId) = either {
        suspendTransaction(db) {
            val crystal = findOrFail(id).bind()
            crystal.toDomainModel().bind()
        }
    }

    private fun findOrFail(id: CrystalId) = either {
        CrystalDaoEntity.findById(id.value.toJavaUuid()) ?: Failure.NotFoundFailure("Not found: $id").left().bind()
    }

    // TODO should ID be generated by DB or domain logic layer?!
    override suspend fun insert(create: CrystalCreate): Either<Failure, Crystal> = either {
        suspendTransaction(db) {
            // TODO use UuidGenerator interface instead (testability); where reside? how install koin?
            CrystalDaoEntity.new(UUID.randomUUID()) {
                weightInGrams = create.weight.value
            }.toDomainModel().bind()
        }
    }

    override suspend fun update(update: CrystalUpdate): Either<Failure, Crystal> = either {
        suspendTransaction(db) {
            val found = CrystalDaoEntity.findByIdAndUpdate(update.id.value.toJavaUuid()) {
                it.weightInGrams = update.weight.value
            } ?: Failure.NotFoundFailure("Not found for update: ${update.id}").left().bind()
            found.toDomainModel().bind()
        }
    }

    override suspend fun delete(id: CrystalId) = either {
        suspendTransaction(db) {
            findOrFail(id).bind().delete()
        }
    }
}

private fun CrystalDaoEntity.toDomainModel() = either {
    Crystal(
        id = CrystalId(id.value.toKotlinUuid()),
        weight = Gram(weightInGrams).bind(),
    )
}
