package nl.uwv.smz.diamond.persistence.impl

/*
internal class CrystalDaoEntity(id: EntityID<UUID>) : UUIDEntity(id) {
    var weightInGrams by CrystalTable.weightInGrams

    companion object : UUIDEntityClass<CrystalDaoEntity>(CrystalTable)
}

internal class CrystalExposedDaoRepo(private val db: Database) : CrystalRepo {

    private val log = logger {}

    override suspend fun selectAll(pageRequest: PageRequest, sorting: CrystalSortingsRequest) = either {
        suspendTransaction(db) {
            log.debug { "selectAll($pageRequest, $sorting)" }
            selectCrystalsWith(pageRequest, sorting).bind()
        }
    }

    override suspend fun selectById(id: CrystalId) = either {
        suspendTransaction(db) {
            val crystal = findOrFail(id).bind()
            crystal.toDomainModel().bind()
        }
    }

    private fun findOrFail(id: CrystalId) = either {
        CrystalDaoEntity.findById(id.value.toJavaUuid()) ?: Failure.NotFoundFailure("Not found: $id").left().bind()
    }

    // TODO should ID be generated by DB or domain logic layer?!
    override suspend fun insert(create: CrystalCreate): Either<Failure, Crystal> = either {
        suspendTransaction(db) {
            // TODO use UuidGenerator interface instead (testability); where reside? how install koin?
            CrystalDaoEntity.new(UUID.randomUUID()) {
                weightInGrams = create.weight.value
            }.toDomainModel().bind()
        }
    }

    override suspend fun update(update: CrystalUpdate): Either<Failure, Crystal> = either {
        suspendTransaction(db) {
            val found = CrystalDaoEntity.findByIdAndUpdate(update.id.value.toJavaUuid()) {
                it.weightInGrams = update.weight.value
            } ?: Failure.NotFoundFailure("Not found for update: ${update.id}").left().bind()
            found.toDomainModel().bind()
        }
    }

    override suspend fun delete(id: CrystalId) = either {
        suspendTransaction(db) {
            findOrFail(id).bind().delete()
        }
    }
}

private fun CrystalDaoEntity.toDomainModel() = either {
    Crystal(
        id = CrystalId(id.value.toKotlinUuid()),
        weight = Gram(weightInGrams).bind(),
    )
}
*/
