package nl.uwv.smz.diamond.persistence.impl

import arrow.core.Either
import arrow.core.left
import arrow.core.raise.either
import arrow.core.right
import nl.uwv.smz.diamond.domain.failure.Failure
import nl.uwv.smz.diamond.domain.model.Crystal
import nl.uwv.smz.diamond.domain.model.CrystalCreate
import nl.uwv.smz.diamond.domain.model.CrystalId
import nl.uwv.smz.diamond.domain.model.CrystalUpdate
import nl.uwv.smz.diamond.domain.model.Gram
import nl.uwv.smz.diamond.domain.model.Page
import nl.uwv.smz.diamond.domain.model.PageMeta
import nl.uwv.smz.diamond.domain.model.PageRequest
import nl.uwv.smz.diamond.persistence.api.CrystalRepo
import org.jetbrains.exposed.dao.UUIDEntity
import org.jetbrains.exposed.dao.UUIDEntityClass
import org.jetbrains.exposed.dao.id.EntityID
import org.jetbrains.exposed.sql.Database
import org.jetbrains.exposed.sql.SqlExpressionBuilder.eq
import org.jetbrains.exposed.sql.deleteWhere
import java.util.UUID
import kotlin.uuid.toJavaUuid
import kotlin.uuid.toKotlinUuid

internal class CrystalDao(id: EntityID<UUID>) : UUIDEntity(id) {
    var weightInGrams by CrystalTable.weightInGrams

    companion object : UUIDEntityClass<CrystalDao>(CrystalTable)
}

fun <T> List<T>.toPage(pageRequest: PageRequest) = Page(
    meta = PageMeta(
        skip = pageRequest.skip,
        take = pageRequest.take,
        hasMore = false, // FIXME
    ),
    items = this,
)

internal class CrystalExposedDaoRepo(private val db: Database) : CrystalRepo {

    override suspend fun selectAll(pageRequest: PageRequest) = either {
        suspendTransaction(db) {
            // FIXME implement skip, take
            CrystalDao.all().map { it.toDomainModel().bind() }
        }.toPage(pageRequest)
    }

    override suspend fun selectById(id: CrystalId) = either {
        suspendTransaction(db) {
            CrystalDao
                .find { CrystalTable.id eq id.value.toJavaUuid() }
                .map { it.toDomainModel().bind() }
                .ensureSingleFound(id.value)
                .bind()
        }
    }

    // TODO should ID be generated by DB or domain logic layer?!
    override suspend fun insert(create: CrystalCreate): Either<Failure, Crystal> = either {
        suspendTransaction(db) {
            CrystalDao
                // TODO use UuidGenerator interface instead (testability); where reside? how install koin?
                .new(UUID.randomUUID()) {
                    weightInGrams = create.weight.value
                }.toDomainModel()
                .bind()
        }
    }

    override suspend fun update(update: CrystalUpdate): Either<Failure, Crystal> = either {
        suspendTransaction(db) {
            val found = CrystalDao.findByIdAndUpdate(update.id.value.toJavaUuid()) {
                it.weightInGrams = update.weight.value
            } ?: Failure.NotFoundFailure("Not found for update: ${update.id}").left().bind()

            found
                .toDomainModel()
                .bind()
                .right()
                .bind()
        }
    }

    override suspend fun delete(id: CrystalId) = either {
        suspendTransaction(db) {
            val deletedCount = CrystalTable.deleteWhere {
                CrystalTable.id eq id.value.toJavaUuid()
            }
            ensureSingleAffected(deletedCount, id.value) { }.bind()
        }
    }
}

private fun CrystalDao.toDomainModel() = either {
    Crystal(
        id = CrystalId(id.value.toKotlinUuid()),
        weight = Gram(weightInGrams).bind(),
    )
}
