apiVersion: v1
kind: Pod
metadata:
  name: my-nginx-pod
  labels:
    app: my-nginx-pod
    env: acceptance
    tier: frontend
spec:
  containers:
    - name: my-nginx-container
      image: nginx
      env:
        - name: ENV_VAR_NAME
          value: ENV_VAR_VALUE
      imagePullPolicy: IfNotPresent
      # otherwise we are warned for being a "noisy neighbor"
      resources:
        requests:
          memory: "64Mi"
          cpu: "250m"
        limits:
          memory: "128Mi"
          cpu: "500m"
  nodeSelector:
    disktype: ssd
