= Declaration of Dependencies

[QUESTION]
====
How to properly declare and centralize the vast amount of dependencies (including version numbers)?
====

[TIP]
====
Status: Proposed +
Created: 1.12.2025 +
Author: Seepick
====

*Context*

* Having versions repeatedly being declared, there is a danger of a mismatch (same library, different versions).
** The mismatch might lead to runtime errors due to binary incompatibility (`NoSuchMethodError`, etc.).
** This is especially true for multi-module projects.
* It's also cumbersome to type and not DRYing; we want to be concise and fast.

*Requirements*

* Not abstracting/hiding too much (e.g. one god dependency), but be explicit/transparent enough for understanding.
** Not too complex, no over-engineering, just get it "good enough"
** Be concise enough, while capturing the essence for clarity (intuitive comprehension) sake.
* Deal with a huge amount of versions, dependencies, and plugins.
* Allow for easy custom plugin declaration (to share common code as extensions/compositions) can use it as well.

Either use Gradle's standard version catalog or write custom code in `buildSrc`.

*Gradle Version Catalog*

* GOOD:
** It's a out-of-the-box supported solution, people know it, well documented.
** Allows for grouped dependencies, so-called libraries.
* BAD:
** TOML syntax for declaration is not as useful as code: auto-completion, type feedback, etc.
** Going into source implementation/definition not possible (CTRL+click), cumbersome...
** If refactoring/changing a dependency, then have to do a step-by-step error-fixing with each build, cumbersome...

.Example of a Gradle version catalog TOML file

[source,toml]
----
[bundles]
ktor = ["ktor-core", "ktor-json", "ktor-foobar"]

[plugins]
short-notation = "some.plugin.id:1.4"
versions = { id = "com.github.ben-manes.versions", version.ref = "manes-versions" }
----

*Custom `buildSrc` Code*

* GOOD:
** It's plain Kotlin code with all its advantages:
*** Immediate feedback from compiler if something is wrong.
*** Refactoring safe.
*** Go to source with CTRL+click (including JavaDoc).
** Full control and flexibility (custom made solution).
** Declaring dependencies here is low-cost as convenient plugins are already using this mechanism.
*** BUT: It is NOT possible to use things from the catalog for those!
* BAD:
** It's custom made for something a default solution already exists; not known.
** Minor: Doesn't support view usages.

.Version declaration in `buildSrc/Version.kt`

[source,kotlin]
----
object Versions {
    const val java = 17
    val kotlin = "2.2.21"
    val ktor = "3.3.2"
    val koin = "4.1.1"
    object logging {
        val kotlin = "7.0.13"
        val logback = "1.5.18"
    }
    object testing {
        val kotest = "6.0.5"
        val cucumber = "7.32.0"
    }
    // ...
}
----

.The `buildSrc/Deps.kt` abstracting dependency coordinates as an object graph
[source,kotlin]
----
object Deps {
    val arrowCore = "io.arrow-kt:arrow-core:${Versions.arrow}"
    object database {
        val h2 = "com.h2database:h2:${Versions.h2}"
        object liquibase {
            val core = "org.liquibase:liquibase-core:4.31.1"
            val slf4j = "com.mattbertolini:liquibase-slf4j:5.1.0"
        }
        object exposed {
            private fun make(artifact: String) = "org.jetbrains.exposed:exposed-$artifact:${Versions.exposed}"
            val jdbc = make("jdbc")
            val datetime = make("java-time")
        }
    }
    // ...
}
// Reference your dependencies as such:
dependencies {
    implementation(Deps.database.exposed.jdbc)
}
----

*Decision*

* Custom approach seems more convenient, safe, and concise.
* Both support grouping and a nested-hierarchy to control a vast amount of declarations.
* Both support auto-completion (for usage, TOML not for declaration).

*Resources*

* https://docs.gradle.org/current/userguide/version_catalogs.html
