= Generating Sources

[QUESTION]
====
Should we regenerate sources each time and host the code next to our own, or should be pre-generate and store them in a dedicated repository?
====

[TIP]
====
Status: Proposed +
Created: 6.12.2025 +
Author: Seepick
====

*Context*

* We use specifications to document the contract, provided for our own API and by third parties.
* Primarily OpenAPI YAML and WSDL XML files need to be generated into usable code (keep in sync).
* It is time-consuming and error-prone to keep code and spec in sync manually.
** Thus the code needs to be generated (assumption), and the question is what's the best way to do it?

*Options*

Re-generate/Insourcing:

* GOOD:
** Everything is self-contained, encapsulated one unit
** Faster to change, as simple/less "bureaucracy"
* BAD:
** Slows down the build process due to regeneration despite no API changes (caching somehow possible?).
** Quality False Positives: Exclusion configuration necessary for static code analysis, coverage, etc. (different rules apply to them)

Pre-generate/Outsourcing:

* Move spec and generated code in an own GIT repository and add a dependency for it.
* GOOD:
** Leads to more safety/stability: A change of the API contract must be a conscious act (not just by accident).
** Faster build times.
** Divide and conquer; manage the bigger complexity by outsourcing; split things apart, separation of concerns.
** Represents the actual reality regarding own API: The contract being a shared artifact (with testers and clients); our application just an implementation of an interface, thus not owned by us.
* BAD:
** Slower development time, having to touch several code bases.
** More complex: separate repositories, version/release management -requires high degree of automation!
** Not everything is achievable with code generation (at least not with realistic effort); some needs to be handwritten.
* For 3rd party APIs, we would expect a given SDK anyways... so we do it ourselves ;)

*Decision*

* Pre-generate.
** Will reduce crucial build time -KPI!
** Simplifies quality analysis (detekt, coverage) tools; keeps our codebase clean and slim.
