= Cucumber Datatable Serialization

[QUESTION]
====
How to convert Cucumber data tables conveniently into a type-parametrized list?
====

[TIP]
====
Status: Accepted +
Created: 11.12.2025 +
Author: Seepick
====

*Context*

* When we define data in a test as a table, we need a simple mechanism to transform this data to a typed result.
* Writing it by hand is cumbersome and slow, a library needs to easily declare and integrate.

.Example of an assertion using a data-table
[source,gherkin]
----
Then the response posts are
  | id | title |
  | 1  | foo   |
  | 2  | bar   |
----

The corresponding code should allow an intuitive solution like this:

.Cucumber step definition to auto-transform data-tables to typed lists
[source,kotlin]
----
@Then("the response posts are")
fun `Then the response posts are`(posts: List<PostDtoRow>) {
    // operate on posts
}
----

*Decision*

* Not much for Kotlin...
* Gladly there is a flawless Kotlin-Java interoperability, so fallback to a Java library:
** See: https://dzone.com/articles/automating-cucumber-data-table-to-java-object-mapping
** Add the dependency `io.github.deblockt:cucumber-datatable-to-bean-mapping` and declare the data table.

.Source to integrate a "Java-native" library in a mixed approach
[source,java]
----
@DataTableWithHeader
public record PostDtoRow(@Column int id, @Column String title) {
}
----
