ifndef::adrsdir[]
include::../local_include.adoc[]
endif::[]

= Test Techstack

include::{adrsdir}/testing/test-framework.adoc[leveloffset=+1]

=== Kotest Inclusion Example

.Defining a test factory with Kotest, which can be included by a test and also includes itself further (generic pagination) tests
[source,kotlin]
----
fun crystalRepoTest(
    dbListener: DbListener,
    repoProvider: (Database, Uuid, LocalDateTime) -> CrystalRepo,
) = describeSpec {
    // ...
    include(
        paginationRepoTests(
            dbProvider = { dbListener.db },
            repoProvider = repoProvider,
            inserter = { repeat(it) { insert(Arb.crystal().next()) } },
            paginatedRepoCall = { selectAll(it, CrystalSortingsRequest.empty()) },
        ),
    )
    describe("Sorting") {
        it("Simple asc") {
            insert(crystal1.copy(weight = 2.gram))
            insert(crystal2.copy(weight = 1.gram))

            repo().selectAll(PageRequest.default(), sort(CrystalSortField.WeightInGram to SortDirection.Asc))
                .shouldBeRight().map { it.weight.value } shouldContainInOrder listOf(1, 2)
        }
    }
    // ...
}
----

.Reuse of includeable tests and plugging in different databases
[source,kotlin]
----
class CrystalExposedDboRepoInmemoryTest : DescribeSpec({
    configureRepoTests(InmemoryDbListener())
})
@RequiresTag(KoTags.testcontainersName)
class CrystalExposedDboRepoTestcontainersTest : DescribeSpec({
    configureRepoTests(TestcontainersDbListener())
})

private fun DslDrivenSpec.configureRepoTests(dbListener: DbListener) {
    extension(dbListener)
    include(
        crystalRepoTest(dbListener) { db, uuid, now ->
            CrystalExposedDboRepo(db, StaticUuidGenerator(uuid), StaticClock(now))
        },
    )
}
----

include::{adrsdir}/testing/mocking.adoc[leveloffset=+1]

== Assertions

include::{adrsdir}/testing/assertion-matchers.adoc[leveloffset=+2]

include::{adrsdir}/testing/assert-json.adoc[leveloffset=+2]

include::{adrsdir}/testing/test-instances.adoc[leveloffset=+2]

== Cucumber

include::{adrsdir}/testing/cucumber-lambdas.adoc[leveloffset=+2]

include::{adrsdir}/testing/cucumber-datatable.adoc[leveloffset=+2]

== Wiremock

We use Wiremock to fake HTTP calls in System Integration Tests.
Due to the `extern-stub` abstraction, this tool won't be used much.
Complementary tests, testing the `extern-impl` on an integration level in isolation (strange contradicting phrasing?!) will require Wiremock.

For integration tests (Cucumber) we use the `extern-stub` implementation to fine-control behavior (and also improve execution time).
A test can also override the stub with custom mocked instances.
