= Generate Configuration Doc

[QUESTION]
====
How to provide easy-to-access documentation of the application configuration (env vars) in an comfortable and automated way?
====

[TIP]
====
Status: Accepted +
Created: 1.12.2025 +
Author: Seepick
====

*Context*

* When deploying our software and it requires quite some configuration values, this information needs to be communicated to operations.
* Everything done manually sucks (and is error-prone); to reduce effort and risk, it is necessary to automate this process.

*Proposal*

Represent the whole "configuration tree" as a plain data class and add custom annotations providing metadata for the documentation generation process.

.Annotated configuration object
[source,kotlin]
----
data class KtorConfig(
    @ConfigProperty("Webserver HTTP port to listen to")
    val port: Int = 8080,
)
----

This can be read via reflection and a simple generator creates a file, which will then be included in the documentation.

.Generated AsciiDoc code for the available environment variable configuration options
[source,asciidoc]
----
|===
|Param |Type |Default |Description

|`KTOR_PORT`
|integer
|8080
|Webserver HTTP port to listen to
|===
----

See the result here: https://seepick.github.io/diamond/#environment-variables
