= Layer Granularity

[QUESTION]
====
Should the modules `view-routing` and `view-controller-api/impl` be separate or merged?
====

[TIP]
====
Status: Proposed +
Created: 5.12.2025 +
Author: Seepick
====

*Separate*

* Adds complexity, more code to write; (already heavy due to route - controller - domain - persist/extern)
** Have to change the controller interface, the controller impl, and potentially register Koin bean, ...
* Adding another abstraction layer leads to more clean architecture (enforced).
** The `view-route` only purpose is, to interact with the web framework specifics, and leave that context immediately.
** Very easy to (semi-unit) test routes (only mock controllers)
* The biggest need-driven reason is from testing point of view:
** Tests cutting into controller, thus no HTTP request/response mechanism is involved
** Making testing extremely fast (runtime performance and development time) and simple (plain code).
*** From Cucumber point of view this is an implementation detail (interchangable, spec stays robust).
** It's simpler, it's more focused, faster, ... but less close to "reality" (higher risk!)
*** It requires complementary tests (route only tests) and integration test of those layers.

*Merged*

* faster development; less code/complexity
* unit (integration, as they use ktor) test for routes will be heavier.

*Decision*

* If the integration tests use HTTP (and not the controllers), then the modules should be merged (less strict but faster).
** Otherwise it would add complexity without using its the benefits.
