= Database Access Library

[QUESTION]
====
Which (JDBC) library to use to access entities from the database in a convenient way?
====

[TIP]
====
Status: Accepted +
Created: 1.12.2025 +
Author: Seepick
====

*Context*

* We need a way to access relational database from Kotlin code.
** We talk about DB access (as in JDBC), not a full ORM solution.
* Requirements:
** Needs to be type-safe (no "stringly-typed" expressions)
** Little/no code generation magic (explicit, in control, safe and stable)
** Kotlin-idiomatic (coroutines, DSLs)
*** For using coroutines we would need a non-blocking implementation (no JDBC)

*Options*

. link:https://www.jetbrains.com/exposed/[Exposed,window=_blank] by JetBrains
** Lightweight and typesafe; Kotlin-first ORM/SQL DSL
** Great for schema-first development.
** Production ready; mature and stable enough.
. JOOQ
** No
. https://www.ktorm.org[KTorm,window=_blank]
** ORM mapper for Kotlin, pure JDBC
. JPA / Hibernate
** Heavyweight, not Kotlin-idiomatic
** Lots of magic, code generation, proxies, etc.

*Decision*

* Exposed; it fits with the rest of the used ecosystem.
* We use the conventional DSL, not the DAO API (seem unfinished).

.Example of Exposed's table schema definition
[source,kotlin]
----
object CrystalTable : UUIDTable("CRYSTALS", "ID") {
    val created = datetime("CREATED")
    val weightInGrams = integer("WEIGHT_IN_GRAMS")
}
----

.Example of Exposed's (favored) DSL API
[source,kotlin]
----
override suspend fun selectById(id: CrystalId) = suspendTransaction(db) {
    either {
            CrystalTable.selectAll()
                .where { CrystalTable.id eq id.value }
                .map { Crystal.byRow(it).bind() }
                .ensureSingleFound(id.value).bind()
    }
}
----

.Example of Exposed's (unfavored) DAO API
[source,kotlin]
----
// definition
class CrystalDaoEntity(id: EntityID<UUID>) : UUIDEntity(id) {
    var weightInGrams by CrystalTable.weightInGrams
    companion object : UUIDEntityClass<CrystalDaoEntity>(CrystalTable)
}
// usage
CrystalDaoEntity.findById(id)
CrystalDaoEntity.new(UUID.randomUUID()) {
    weightInGrams = 42
}
CrystalDaoEntity.findByIdAndUpdate(id) {
    it.weightInGrams = 42
}
----

*Resources*

* https://stackoverflow.com/questions/70734941/exposed-orm-dsl-vs-dao-in-many-to-many-relationships-best-practices
