apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../../base

resources:
  - more.deployment.yaml

components:
  - ../../components/caching

patches:
  - target:
      kind: Deployment
      name: my-api-deployment
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 5