apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-db-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-db-pod
  template:
    metadata:
      labels:
        app: my-db-pod
    spec:
      containers:
        - name: my-db-container
          image: nginx:1.14.2
          resources:
            requests:
              memory: "64Mi"
              cpu: "200m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 80
