= Code Generation

[QUESTION]
====
// TODO
====

[TIP]
====
Status: Draft +
Created: 11.12.2025 +
Author: Seepick
====

*Context*

* Third parties (and our own API as well) provide a markup document (JSON, YAML or XML) specifying their API.
* It is time-consuming and error-prone to maintain code and spec in sync manually.
* Code needs to be generated (assumption), and the question is what's the best alternative to do it?

*Insourcing*

* Everything encapsulated into one unit; faster development, less "bureaucracy".
* The generated sources will most likely not comply with configured static code analysis and formatting tools and cause false positives.
* Regenerating sources every build costs precious (build/developer) time and is 99% of the cases not necessary (no changes).

*Outsourcing*

* Tool enforced contract compliance (more robust).
* A change in the API is a deliberate act (and not an accident); higher impact, more sensitive.
* But it is *especially true* for our own API, that the spec is not part of the backend-service; it is shared with frontend and testers; it's the contract to which we provide an implementation for.
* Not everything is achievable with code generation (at least not with realistic effort); some needs to be handwritten.
