= Explicit Exception Handling

[QUESTION]
====
// TODO
====

[TIP]
====
Status: Draft +
Created: 1.12.2025 +
Author: Seepick
====

*Context*

* Ever since the time when the Spring Framework got popular, unchecked exceptions were favored over checked ones.
(Neil Gafter, Josua Bloch)
** Kotlin goes one step further, and treats all exceptions as unchecked ones.
* Throwing exceptions is a sort of an implicit return value, which can be forgotten to be handled properly (resulting in false-500 responses).

.Implicit exceptions are easily forgotten and unhandled
[source,kotlin]
----
fun Service.dangerousMethod(): Result {
    throw RuntimeException()
}
fun Route.handleGet(): ServerResponse {
    val result = service.dangerousMethod()
    return toResponse(result)
}
----

*Proposal*

* Use the link:https://arrow-kt.io/[Arrow library] to introduce a more functional approach, its `Either` type specifically.

.Explicit fault handling cannot be forgotten nor unhandled
[source,kotlin]
----
fun Service.dangerousMethod(): Either<Failure, Result> {
    // do some real logic ...
    return Failure().left()
}
fun handleGet(): ServerResponse =
    service.dangerousMethod().fold(
        ifLeft = { toFailResponse(it) }, // <1>
        ifRight = { toResponse(it) },
    )

----

<1> in order to access the result, we need to unwrap both, which is already known via Java's `Optional.ifPresentOrElse`

* Good:
** developers need to think (forced to, explicit) error types, mapping of them (translation of corrupt data to bad request/internal error)
** supports DDD by simulating failure-aware constructors (companion operator fun with Either return type)
* Bad:
** sometimes not clear if not familiar with it
** sometimes IDE doesn't suggest `.bind()` although it's the solution
