apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - api.config.yaml
  - api.deployment.yaml
  - api.service.yaml

labels:
  - pairs:
      subproject: api
    includeSelectors: true
