apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - api/
  - db/

namespace: my-ns
namePrefix: kaml-
nameSuffix: -demo


labels: # NOT commonLabels (deprecated)
  - pairs:
      project: my-kustomize-project
    includeSelectors: true
commonAnnotations:
  some.foobar.io: config-value

# TODO couldn't get it to working?!
images:
  - name: nginx
  - newName: haproxy
  - newTag: 1.2.3
