ifndef::adrsdir[]
include::../local_include.adoc[]
endif::[]

= Techstack

Library choice guidelines:

* Kotlin-idiomatic (DSLs, functional)
* Asynchronous (native coroutine support)
* Alive project (recent commit to repo)
* Non-intrusive (clean code, no coupling)
* Code over Config (incl. annotations)

As a golden rule, there should never be any *non-production dependencies* (test, stubs, localdev, etc like H2) in production code.
Instead activate profiles which customize the build (dependency tree).
E.g. for tests (presistence-tests and itests) different wiring

== Libraries

.A list of all used dependencies can be found at: link:https://github.com/seepick/diamond/blob/main/buildSrc/src/main/kotlin/Deps.kt[buildSrc/Deps.kt]
[source,kotlin]
----
object Deps {
    val arrowCore = "io.arrow-kt:arrow-core:${Versions.arrow}"
    val jsch = "com.github.mwiede:jsch:${Versions.jsch}"
    object database {
        val h2 = "com.h2database:h2:${Versions.h2}"
        object exposed {
            private fun make(artifact: String) = "org.jetbrains.exposed:exposed-$artifact:${Versions.exposed}"
            val jdbc = make("jdbc")
            val datetime = make("java-time")
        }
    }
    // ...
}
----

=== General

Gradle:: Build system to run tasks such as compiling, testing, and packaging ("_newer Maven_", using its sophisticated dependency management).
Kotlin:: General purpose programming language running on the JVM ("_newer Java_", fully interoperable).

include::{adrsdir}/libraries/dependency-injection.adoc[leveloffset=+3]

include::{adrsdir}/libraries/datetime.adoc[leveloffset=+3]

=== Web

Ktor:: Lightweight web framework ("_newer Spring WebMVC_") and client.
Serializationx:: Kotlin specific JSON serialization (instead of Jackson).

include::{adrsdir}/libraries/dto-mapping.adoc[leveloffset=+3]

include::{adrsdir}/libraries/serialization.adoc[leveloffset=+3]

=== Persistence

Exposed:: Typesafe SQL library (not a full fledged ORM like JPA/Hbernate).
Liquibase:: Database migration library using XML.
H2:: As an in-memory database for testing and local development.

include::{adrsdir}/persistence/database-library.adoc[leveloffset=+3]

include::{adrsdir}/persistence/migration.adoc[leveloffset=+3]

=== Test

Kotest:: Modern flexible testing framework integrating with the JUnit engine ("_newer JUnit_")/
Cucumber:: BDD framework to write integration tests with Gherkin.
Kover:: Test coverage tool, generating JaCoCo compatible XML reports.
Mockk:: Kotlin-idiomatic mocking framework.
WireMock:: Complex backend call mocking.
Testcontainers:: To locally spin-up docker containers for system integration tests.

=== Quality

SonarQube:: Quality gate for code analysis, test coverage and more.
Detekt:: Static code analysis together ("_newer CheckStyle_")
Ktlint:: Auto-formatter, integrated via Detekt.
OWASP:: Vulnerability dependency scanner.

=== Supportive

Koin:: Dependency injection, actually service locator, framework ("_newer Spring Framework_", neither classpath scanning nor annotations use).
Arrow:: Functional library used for link:https://proandroiddev.com/how-to-use-arrows-either-for-exception-handling-in-your-application-a73574b39d07[better exception handling] via `Either`.
link:https://github.com/sksamuel/hoplite[Hoplite]:: Typesafe loading of application configuration.

include::{adrsdir}/technologies/scheduler.adoc[leveloffset=+3]

include::{adrsdir}/technologies/message_queue.adoc[leveloffset=+3]

include::{adrsdir}/technologies/sftp-service.adoc[leveloffset=+3]
