== Development

* run `nl.uwv.smz.diamond.app.LocalDiamondApp`
* Postman collection can be found at: `/local/Diamond.postman_collection.json`

IntelliJ plugins:

* Gradle
* EditorConfig
* detekt - configure with `/config/detekt.yml`
* ktlint
* kotest
* Markdown
* AsciiDoc
* plantuml4idea (graphivz/dot required)
* Gherkin
* Cucumber for Kotlin
* Cucumber for Java
* Cucumber+
* Cucumber Table Mapping
* kotlin-fill-class

=== Gradle

Sharing build logic via the `buildSrc` directory.

See: https://docs.gradle.org/current/userguide/sharing_build_logic_between_subprojects.html

==== Gradle Properties

Pass them either as `-P` (precendence) or `-D`.

* `diamond_version` - application version, defaults to `0` if not specified
** displayed in info endpoint, used in generated documentation
* `runTestcontainersTests` - see task below
* `runEtests` - see task below

==== Gradle Tasks

* `./gradlew :app:buildFatJar -Pdiamond_version="42"` - build a standalone, executable Jar
* `./gradlew :app:generateConfigDoc` - custom task which generates the asciidoc for the config table (available env vars)
* `./gradlew :doc:SoftwareDocument:asciidoctorPdf`
* `./gradlew test -PrunTestcontainersTests=true` - run only the tests requiring testcontainers (docker; oracle)
* `./gradlew test -PrunEtests=true` - run the Karate tests located in the `etest` subproject
* `./gradlew dependencyUpdates` - to check for outdated dependencies (help category, using manes plugin)
* `./gradlew publishImageToLocalRegistry` or `runDocker` (or `publishImage` once remote registry is configured)
