= Endpoint Versioning

[QUESTION]
====
How to support multiple API versions simultaneously?
====

[TIP]
====
Status: Proposed +
Created: 1.12.2025 +
Author: Seepick
====

*Context*

* When backend and frontend deploy independently (which is supposed to be), they might run out of sync with the contract.
** There needs to be a way to introduce breaking changes yet not break the clients.
** The API needs to be able to be versioned (specified by the client), behaving in different ways based on the version used.
* Also think of a deprecation strategy, the roadmap needs to be easily visible (communicated, dashboards) for the clients.
** E.g. tag OpenAPI spec as deprecated; add warnings in generated code possible.
** Keep track (logging, dashboards) of usage of each version by clients, to know when it is safe to turn it off (or nudge clients).

*Options*

. Either using the accept header to specify a custom mime type
** E.g. `Accept: application/vnd.diamond.crystal.v1+json` and `Content-Type: ...`
** This keeps the URLs clean, and metadata is stored properly in headers as supposed to be.
** But not so obvious at first; also requires additional logic to be implemented.
. Or encode the version in path: `GET /api/v1/crystals` (this is the more common approach)
** Explicit, flexible, simple.
** Out-of-the-box supported by caching.

*Decision*

* Encoding the version in the path.
More common, simpler.

*Links*

* https://dev.to/abhivyaktii/api-versioning-using-headers-a-clean-and-flexible-approach-218p
