ifndef::adrsdir[]
include::../local_include.adoc[]
endif::[]

== Introduction

=== Purpose

This project is a state-of-the-art prototype of a backend service, which can be used as a laboratory to gain experience (elaborating further on this proof-of-concept), a base for technical decision making and a template for future reference.

This document describes not only the specifics of this implementation (a tangible, hands-on, experience-based source of information using a concrete example instead of hypothetical theorization), but also the underlying principles, representing best practices.
It ends with an outlook on open doings and a future vision on how to shape also the broader picture of integration, deployment, monitoring, etc.

=== Decision Documentation

We use ADRs (Architecture Decision Records) to document important architectural and technical decisions made during the development of this software project.

For more explanation what ADRs are, please read: https://github.com/seepick/diamond/blob/main/doc/decisions/README.adoc

// TODO show high-level overviews & diagrams


