ifndef::adrsdir[]
include::../local_include.adoc[]
endif::[]

= Best Practices

A quick flush of some brainstorm thoughts around what could be considered relevant; please don't give too much meaning to it...

== Coding Hints

* Strive for functional, e.g.: *pure functions*:
** return values are identical for identical arguments (no variation with static variables, non-local variables, mutable reference arguments or input streams, i.e., referential transparency)
** the function has no side effects (no mutation of non-local variables, mutable reference arguments or input/output streams)
* no overloaded methods, provide different name
* instead of regular methods -> "named expressions"
** functions as named codeblocks, lead to shorter (easier to comprehend) methods
** always use "=" after method signature; single expression body
** no state, no "val" keyword, all just immediate execution (more functional)
** forces to write very short methods, easy to read and comprehend
** methods have names, they create logical structure of arbitrary code

=== Coding Philosophy

* fail early, fail fast
* e.g. if application config something is configured wrong/missing
* validate data (front incoming HTTP, back external systems/DB, immediately throw)
* code first / code over markup
** no strings/annotations, no declarative xml/json/yaml/properties
*** see programmatic logging configuration DSL (reuse, parametrizable) instead of the usual, static `logback.xml`
** just code, be in control, flexible, safe (compiler reference check)
* no classpath scanning, reflection, other look-ups/service-locator, no auto-magically something
* avoid intrusive frameworks (the systems serves us, we don't serve the system)
* functional programming
* pure functions: stateless, side-effect free
* code as named expressions
* prefer single-expression-method `fun foo() = doSome().doOther().also { done(it) }`
* absolutely no local files (IDE specific, build generated, ...)
** not checked in, even existing put on .gitignore
** all auto-configured by build system/gradle
** don’t interfere with each other; give devs freedom - no coupling
* single responsibility (of package, class, method/function)
* clear names, self-explanatory, capturing its essence (single responsibility)
** no abbreviations, no short cryptic names
* be aware of the difference between integration-code (tech/infra; tested by integration tests) and application-code (business, domain; tested by unit tests)
** it's a smell if unit tests have a lock of mocking going on; trying to unit test integration code

== Specific Topics

This section can be expanded to address specific development related topics in more detail.

=== Conciseness

Using type inference and link:https://kotlinlang.org/docs/functions.html#single-expression-functions[single expression functions], function declarations can be shortened and made more readable:

.Ommitting the return type
[source,kotlin]
----
fun `BAD explicit`(): String = "foo"

fun `GOOD inferred`() = "foo"
----

.Using lambda wrappers
[source,kotlin]
----
fun `BAD increase indentation`() {
    transactional {
        repo.update()
    }
}

fun `GOOD single expression`() = transactional { // <1>
    repo.update()
}
----

<1> Sometimes needed to override inferred type to `: Unit`.

.Using standard functionals
[source,kotlin]
----
fun Service.`BAD return`(): Service {
    setFoo("bar")
    return this
}

fun Service.`GOOD apply`() = apply {
    setFoo("bar")
}
----

include::{adrsdir}/coding/explicit_exception_handling.adoc[leveloffset=+2]

== Logging

include::{adrsdir}/libraries/logging-configuration.adoc[leveloffset=+2]

include::{adrsdir}/libraries/logging-with-kotlin.adoc[leveloffset=+2]
