name: Continuous Integration
on:
  push:
    branches:
      - main
jobs:
  gradle:
    name: Build Gradle project
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
      - name: Check Project
        run: ./gradlew check
      - name: Build SAD
        run: ./gradlew :doc:SoftwareDocument:asciidoctorPdf
