name: Nightly
on:
  workflow_dispatch: # invoke manually
#  schedule:
#    - cron: '0 0 * * *' # daily at 00:00 UTC
permissions:
  contents: read
  actions: read
jobs:
  gradle:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
      - uses: actions/setup-gradle@v4
      - name: Run Gradle checks
        run: |
          ./gradlew check 
          -DisCi
          -DenableOwasp
#           enable for more sophisticated check (and more breaking builds ;)
#          -DowaspOssUsername=${{ secrets.OWASP_OSS_USERNAME }}
#          -DowaspOssPassword=${{ secrets.OWASP_OSS_PASSWORD }}
# dependencyCheckAggregate ?
