name: Nightly
on:
  workflow_dispatch: # invoke manually
  schedule:
    - cron: '0 0 * * *' # daily at 00:00 UTC
permissions:
  contents: read
  actions: read
jobs:
  gradle:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
      - uses: actions/setup-gradle@v4
      - run: ./gradlew check -DenableOwasp -DisCi
