name: Build Release

on:
  push:
    tags:
      - '*'

jobs:
  prepare-release:
    name: Creating GitHub Release
    runs-on: ubuntu-latest
    # https://docs.github.com/en/actions/reference/workflows-and-actions/workflow-syntax#permissions
    permissions:
      contents: write
    steps:
      - name: Create Release # https://github.com/marketplace/actions/create-tag-release
        id: create_release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref_name }}
          body: No changelog provided
          draft: false
          prerelease: false
    outputs:
      upload-url: ${{ steps.create_release.outputs.upload_url }}

  build-and-upload:
    name: Building and uploading artifact
    permissions:
      contents: write
    runs-on: ubuntu-latest
    needs: prepare-release
    steps:
      - name: Log Info
        run: echo "This job is using ref ${{ github.ref }} and ref_name ${{ github.ref_name }}"
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
      - uses: gradle/actions/setup-gradle@v4

      - name: Build JAR
        run: ./gradlew :app:buildFatJar -Pdiamond_version="${{ github.ref_name }}"
      - name: Build SAD
        # TODO add version number/build date to PDF
        run: ./gradlew :doc:SoftwareArchitectureDocument:asciidoctorPdf

      - name: Upload Release Artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.prepare-release.outputs.upload-url }}
          asset_path: app/build/libs/diamond.jar
          asset_name: diamond.jar
          asset_content_type: application/java-archive

      - name: Upload SAD
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.prepare-release.outputs.upload-url }}
          asset_path: doc/SoftwareArchitectureDocument/build/docs/asciidocPdf/index.pdf
          asset_name: Diamond-SoftwareArchitectureDocument.pdf
          asset_content_type: application/pdf
