name: Build Release

on:
  # invoke manually
  workflow_dispatch:
    inputs:
      version:
        description: 'The version number to be used'
        required: true
        default: '2025.12.1'
        type: string

# TODO rearrange
# on: manual-run
# gradlew -DisCi
# verify:
# *) check (tests, detekt)
# *) run/enable advanced tests: docker, ...; -DrunEtests; -DrunTestcontainersTests
# *) OWASP -DenableOwasp
#
# build:
# *) asciidoc
# *) assemble: jar, docker image; -Ddiamond_version; -Ddiamond_branch
# *) increment version, tag code
# *) deploy/release

jobs:
  prepare-release:
    name: Creating GitHub Release
    environment: main
    runs-on: ubuntu-latest
    # https://docs.github.com/en/actions/reference/workflows-and-actions/workflow-syntax#permissions
    permissions:
      contents: write
    steps:
      - name: Create Release # https://github.com/marketplace/actions/create-tag-release
        id: create_release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          #          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.event.inputs.version }}
          body: No changelog provided
          draft: false
          prerelease: false
    outputs:
      upload-url: ${{ steps.create_release.outputs.upload_url }}

  build-and-upload:
    name: Building and uploading artifact
    environment: main
    runs-on: ubuntu-latest
    needs: prepare-release
    permissions:
      contents: write
    steps:
      - name: Log Info
        # e.g.: "ref refs/tags/1 and ref_name 1"
        run: |
          echo "The given version number is: ${{ github.event.inputs.version }}"
          echo "This job is using ref ${{ github.ref }} and ref_name ${{ github.ref_name }}"
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
      - uses: gradle/actions/setup-gradle@v4

      - name: Build JAR
        # TODO change version number algorithm here
        run: ./gradlew :app:buildFatJar -Ddiamond_version="${{ github.event.inputs.version }}" -Ddiamond_branch="${{ github.ref}}"
      - name: Generate config documentation
        run: ./gradlew :app:generateConfigDoc
      - name: Build SoftwareDocument PDF
        run: ./gradlew :doc:SoftwareDocument:asciidoctorPdf -Ddiamond_version="${{ github.event.inputs.version }}"

      - name: Upload Release Artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.prepare-release.outputs.upload-url }}
          asset_path: app/build/libs/diamond.jar
          asset_name: diamond.jar
          asset_content_type: application/java-archive

      - name: Upload SoftwareDocument
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.prepare-release.outputs.upload-url }}
          asset_path: doc/SoftwareDocument/build/docs/asciidocPdf/index.pdf
          asset_name: Diamond-SoftwareDocument.pdf
          asset_content_type: application/pdf
