= Challenges

== Parallel Cucumber Tests

* The application needs to be run in total isolation.
** Tricky with Cucumber's deferred nature: step def implementations invoked by the framework, instead a single method encapsulating the whole test.
* First the *Ktor test-engine* was not properly capable of running in a deferred way.
** There is still a minor hack, casting to an internap type to configure the Ktor test-client.
* The the *Koin* application used global shared state (`Koin` to `KoinIsolated` plugin).
* The *Exposed* classes need to always explicitly declare the database to use for each transaction.

== OpenAPI code generation support for Kotlin

* With more popular frameworks like SpringBoot generation is sufficient.
** Need something recent and fitting (actually usable) for Kotlin.
* Generate (ktor KMP) client and server (ktor routes); and optional separate data models (depending on application layering required separately).
** See <<adr_coding_openapigenerator>> for details.
* Automatic SwaggerUI generation.
** Works nicely with Spring, nothing really for Ktor.
